PROMPTS = [
    "What is the capital of France? Answer in one word.",
    "Who won the 2018 World Cup? Answer in one word.",
    "What is the boiling point of water? Answer in one word.",
    "Explain the offside rule in football in one paragraph.",
    "Describe the main features of a combustion engine in one paragraph.",
    "Summarize the plot of the novel '1984' by George Orwell in a short paragraph.",
    "Write a detailed 300-word essay on the causes and effects of climate change.",
    "Discuss the 4-3-3 formation in football. Please answer in an essay format.",
    "Explain the history and significance of the Renaissance period in detail.",
    "Who won the 2018 World Cup?",
    "In detail, describe the tactical formations used in football during the 2018 World Cup, and explain how these impacted the outcomes of key matches.",
    "What is the capital of France?",
    "Explain the offside rule in football in one paragraph.",
    "Write a 300-word essay on climate change.",
    "Who won the 2018 World Cup?",
    "Describe how a combustion engine works.",
]